// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjZtzYOKP705uJfjfcKofWzcJSsyVsHwI',
    appId: '1:86729925177:web:643f5cee448e25421ea3e8',
    messagingSenderId: '86729925177',
    projectId: 'cook-2d028',
    authDomain: 'cook-2d028.firebaseapp.com',
    storageBucket: 'cook-2d028.firebasestorage.app',
    measurementId: 'G-WREHGXEBMR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdXgZr2EgKbuqFHjjncMJ4l-C8EuuQOhs',
    appId: '1:86729925177:android:eaade2cbe37107e81ea3e8',
    messagingSenderId: '86729925177',
    projectId: 'cook-2d028',
    storageBucket: 'cook-2d028.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhfQjTGlt6HSasqKOtHobBIM36mLZV3aM',
    appId: '1:86729925177:ios:fa0322cbfb7d101a1ea3e8',
    messagingSenderId: '86729925177',
    projectId: 'cook-2d028',
    storageBucket: 'cook-2d028.firebasestorage.app',
    iosBundleId: 'com.example.appgreenfood',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhfQjTGlt6HSasqKOtHobBIM36mLZV3aM',
    appId: '1:86729925177:ios:fa0322cbfb7d101a1ea3e8',
    messagingSenderId: '86729925177',
    projectId: 'cook-2d028',
    storageBucket: 'cook-2d028.firebasestorage.app',
    iosBundleId: 'com.example.appgreenfood',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjZtzYOKP705uJfjfcKofWzcJSsyVsHwI',
    appId: '1:86729925177:web:e2b70dc4a8c861221ea3e8',
    messagingSenderId: '86729925177',
    projectId: 'cook-2d028',
    authDomain: 'cook-2d028.firebaseapp.com',
    storageBucket: 'cook-2d028.firebasestorage.app',
    measurementId: 'G-MKGF954YR9',
  );

}